from django.urls import path
from django import urls, views
from . import views

urlpatterns = [
   path('', views.home),
   path('home/', views.home),
   path('entidades/', views.entidades),
   path('create_entidades/', views.createEntidades),
   path('update_entidades/<int:id>/', views.updateEntidades),
   path('delete_entidades/<int:id>/', views.deleteEntidades),
   path('estados/', views.estados),
   path('create_estados/', views.createEstados),
   path('update_estados/<int:id>/', views.updateEstados),
   path('delete_estados/<int:id>/', views.deleteEstados),
   path('departamentos/', views.departamentos),
   path('create_departamentos/', views.createDepartamentos),
   path('update_departamentos/<int:id>/', views.updateDepartamentos),
   path('delete_departamentos/<int:id>/', views.deleteDepartamentos),
   path('unidadesMedidas/', views.unidadesMedidas),
   path('create_unidadesMedidas/', views.createUnidadesMedidas),
   path('update_unidadesMedidas/<int:id>/', views.updateUnidadesMedidas),
   path('delete_unidadesMedidas/<int:id>/', views.deleteUnidadesMedidas),
   path('proveedores/', views.proveedores),
   path('create_proveedores/', views.createProveedores),
   path('update_proveedores/<int:id>/', views.updateProveedores),
   path('delete_proveedores/<int:id>/', views.deleteProveedores),
   path('articulos/', views.articulos),
   path('create_articulos/', views.createArticulos),
   path('update_articulos/<int:id>/', views.updateArticulos),
   path('delete_articulos/<int:id>/', views.deleteArticulos),
   path('ordenCompra/', views.ordenCompra),
   path('create_ordenCompra/', views.createOrdenCompra),
   path('update_ordenCompra/<int:id>/', views.updateOrdenCompra),
   path('delete_ordenCompra/<int:id>/', views.deleteOrdenCompra),
   path('asiento/', views.asiento),
   path('create_asiento/', views.createAsiento),
   path('create_asiento_json/<int:id>/', views.createAsientoJson),
   path('update_asiento/<int:id>/', views.updateAsiento),
   path('delete_asiento/<int:id>/', views.deleteAsiento),
]