# Generated by Django 4.1.7 on 2023-03-06 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('existencia', models.IntegerField()),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_compras.entidades')),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_compras.entidades')),
            ],
        ),
        migrations.CreateModel(
            name='Unidades_Medidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_compras.entidades')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_compras.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=50)),
                ('cedula_rnc', models.CharField(max_length=11)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_compras.entidades')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_compras.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_compras.articulos')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_compras.entidades')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_compras.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_compras.entidades')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_compras.estados')),
            ],
        ),
        migrations.AddField(
            model_name='articulos',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_compras.estados'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_compras.unidades_medidas'),
        ),
    ]
