# Generated by Django 4.1.7 on 2023-03-07 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_compras', '0002_articulos_estados_unidades_medidas_proveedores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados',
            name='entidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sistema_compras.entidades'),
        ),
    ]
