# Generated by Django 4.1.7 on 2023-03-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_compras', '0004_alter_estados_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='cedula_rnc',
            field=models.IntegerField(max_length=11, verbose_name='Cedula o RNC'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nombre_comercial',
            field=models.CharField(max_length=50, verbose_name='Nombre Comercial'),
        ),
    ]
