# Generated by Django 4.1.7 on 2023-03-07 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_compras', '0005_alter_proveedores_cedula_rnc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='cedula_rnc',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)], verbose_name='Cedula o RNC'),
        ),
    ]
