# Generated by Django 4.1.7 on 2023-03-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_compras', '0008_alter_proveedores_cedula_rnc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='cedula_rnc',
            field=models.IntegerField(verbose_name='Cedula o RNC'),
        ),
    ]
