# Generated by Django 4.1.7 on 2023-03-07 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_compras', '0010_alter_proveedores_cedula_rnc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='cedula_rnc',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Cedula o RNC'),
        ),
    ]
