# Generated by Django 4.1.7 on 2023-03-31 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_compras', '0011_alter_proveedores_cedula_rnc'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_compra',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orden_compra',
            name='costo_unitario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orden_compra',
            name='unidad_medida',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sistema_compras.unidades_medidas'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='unidad_medida',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sistema_compras.unidades_medidas'),
        ),
    ]
