# Generated by Django 4.1.7 on 2023-03-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_compras', '0013_orden_compra_id_asiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_asiento_desde', models.DateField()),
                ('periodo_asiento_hasta', models.DateField()),
                ('id_cuenta_db', models.CharField(max_length=10)),
                ('descripcion_db', models.CharField(max_length=40)),
                ('id_cuenta_cr', models.CharField(max_length=10)),
                ('descripcion_cr', models.CharField(max_length=40)),
                ('tipo_movimiento_db', models.CharField(choices=[('Debito', 'Debito'), ('Credito', 'Credito')], max_length=10)),
                ('monto_db', models.IntegerField()),
                ('monto_cr', models.IntegerField()),
                ('transaccion', models.ManyToManyField(to='sistema_compras.orden_compra')),
            ],
        ),
    ]
