# Generated by Django 4.1.7 on 2023-03-31 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_compras', '0014_asiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asiento',
            name='tipo_movimiento_db',
        ),
    ]
